//Loot tables
/datum/loot_table
	var/list/loot = list(
		"common" = list(),
		"uncommon" = list(),
		"rare" = list(),
		"very rare" = list()
	)

/datum/loot_table/bedsheet
	loot = list(
		"common" = list(
			/obj/item/weapon/bedsheet/black,
			/obj/item/weapon/bedsheet/blue,
			/obj/item/weapon/bedsheet/brown,
			/obj/item/weapon/bedsheet/green,
			/obj/item/weapon/bedsheet/medical,
			/obj/item/weapon/bedsheet/orange,
			/obj/item/weapon/bedsheet/purple,
			/obj/item/weapon/bedsheet/red,
			/obj/item/weapon/bedsheet/yellow,
		),
		"uncommon" = list(
			/obj/item/weapon/bedsheet/plaid,
			/obj/item/weapon/bedsheet/clown,
			/obj/item/weapon/bedsheet/linen,
			/obj/item/weapon/bedsheet/mime,
			/obj/item/weapon/bedsheet/rainbow,
		),
		"rare" = list(
			/obj/item/weapon/bedsheet/rd,
			/obj/item/weapon/bedsheet/hop,
			/obj/item/weapon/bedsheet/hos,
			/obj/item/weapon/bedsheet/captain,
			/obj/item/weapon/bedsheet/ce,
		),
		"very rare" = list()
	)

/datum/loot_table/bureaucracy
	loot = list(
		"common" = list(
			/obj/item/toy/crayon/black,
			/obj/item/toy/crayon/blue,
			/obj/item/toy/crayon/green,
			/obj/item/toy/crayon/mime,
			/obj/item/toy/crayon/orange,
			/obj/item/toy/crayon/purple,
			/obj/item/toy/crayon/rainbow,
			/obj/item/toy/crayon/red,
			/obj/item/toy/crayon/yellow,
			/obj/item/weapon/folder,
			/obj/item/weapon/folder/black,
			/obj/item/weapon/folder/blue,
			/obj/item/weapon/folder/green,
			/obj/item/weapon/folder/mime,
			/obj/item/weapon/folder/orange,
			/obj/item/weapon/folder/purple,
			/obj/item/weapon/folder/rainbow,
			/obj/item/weapon/folder/red,
			/obj/item/weapon/folder/white,
			/obj/item/weapon/folder/yellow,
			/obj/item/weapon/gavelblock,
			/obj/item/weapon/gavelhammer,
			/obj/item/weapon/hand_labeler,
			/obj/item/weapon/paper/random,
			/obj/item/weapon/paper_bin,
			/obj/item/weapon/paper_pack,
			/obj/item/weapon/pen,
			/obj/item/weapon/pen/blue,
			/obj/item/weapon/pen/fountain,
			/obj/item/weapon/pen/invisible,
			/obj/item/weapon/pen/red,
			/obj/item/weapon/stamp/denied,
			/obj/item/weapon/storage/photo_album,
		),
		"uncommon" = list(
			/obj/item/weapon/glue/temp_glue,
			/obj/item/weapon/pen/multi,
			/obj/item/weapon/pen/sleepypen,
			/obj/item/weapon/stamp/captain,
			/obj/item/weapon/stamp/ce,
			/obj/item/weapon/stamp/chaplain,
			/obj/item/weapon/stamp/clown,
			/obj/item/weapon/stamp/cmo,
			/obj/item/weapon/stamp/hop,
			/obj/item/weapon/stamp/hos,
			/obj/item/weapon/stamp/hos,
			/obj/item/weapon/stamp/iaa,
			/obj/item/weapon/stamp/judge,
			/obj/item/weapon/stamp/mime,
			/obj/item/weapon/stamp/rd,
			/obj/item/weapon/stamp/trader,
			/obj/item/weapon/stamp/warden,
			/obj/item/weapon/storage/briefcase,
			/obj/item/weapon/storage/briefcase/centcomm,
		),
		"rare" = list(
			/obj/item/weapon/glue,
			/obj/item/weapon/pen/paralysis,
			/obj/item/weapon/pen/tactical,
			/obj/item/weapon/storage/briefcase/insurance,
			/obj/item/weapon/storage/briefcase/orderly,
		),
		"very rare" = list(
			/obj/item/weapon/storage/briefcase/false_bottomed,
		)
	)

/datum/loot_table/clothing
	loot = list(
		"common" = list(
			/obj/item/clothing/under/color/grey,
			/obj/item/clothing/under/color/black,
			/obj/item/clothing/under/color/blue,
			/obj/item/clothing/under/color/green,
			/obj/item/clothing/under/color/red,
			/obj/item/clothing/under/color/white,
			/obj/item/clothing/under/waiter,
			/obj/item/clothing/under/rank/janitor,
			/obj/item/clothing/under/rank/bartender,
			/obj/item/clothing/under/tourist,
			/obj/item/clothing/under/rank/chaplain,
			/obj/item/clothing/under/rank/librarian,
			/obj/item/clothing/under/rank/chef,
			/obj/item/clothing/under/mime,
			/obj/item/clothing/under/clown,
			/obj/item/clothing/shoes/black,
			/obj/item/clothing/shoes/brown,
			/obj/item/clothing/shoes/white,
			/obj/item/clothing/shoes/sandal,
			/obj/item/clothing/shoes/slippers,
			/obj/item/clothing/head/soft,
			/obj/item/clothing/head/soft/red,
			/obj/item/clothing/head/soft/blue,
			/obj/item/clothing/head/fedora,
			/obj/item/clothing/head/fedora/brown,
			/obj/item/clothing/head/headband,
			/obj/item/clothing/head/beret,
			/obj/item/clothing/head/beanie,
			/obj/item/clothing/gloves/fingerless,
			/obj/item/clothing/gloves/botanic_leather,
			/obj/item/clothing/suit/storage/labcoat,
			/obj/item/clothing/suit/jacket,
			/obj/item/clothing/suit/apron,
		),
		"uncommon" = list(
			/obj/item/clothing/under/suit_jacket/really_black,
			/obj/item/clothing/under/suit_jacket/red,
			/obj/item/clothing/under/suit_jacket/navy,
			/obj/item/clothing/under/casualwear,
			/obj/item/clothing/under/keyholesweater,
			/obj/item/clothing/under/varsity,
			/obj/item/clothing/under/hunter,
			/obj/item/clothing/under/rank/security,
			/obj/item/clothing/under/rank/medical,
			/obj/item/clothing/under/rank/scientist,
			/obj/item/clothing/under/rank/engineer,
			/obj/item/clothing/under/rank/roboticist,
			/obj/item/clothing/under/rank/det,
			/obj/item/clothing/under/turtleneck,
			/obj/item/clothing/shoes/laceup,
			/obj/item/clothing/shoes/leather,
			/obj/item/clothing/shoes/athletic,
			/obj/item/clothing/shoes/workboots,
			/obj/item/clothing/head/fedora/white,
			/obj/item/clothing/head/fez,
			/obj/item/clothing/head/flatcap,
			/obj/item/clothing/head/that,
			/obj/item/clothing/head/ushanka,
			/obj/item/clothing/head/trucker,
			/obj/item/clothing/head/beret/sec,
			/obj/item/clothing/head/hardhat,
			/obj/item/clothing/gloves/white,
			/obj/item/clothing/gloves/black,
			/obj/item/clothing/gloves/latex,
			/obj/item/clothing/suit/armor/vest,
			/obj/item/clothing/suit/storage/det_suit,
			/obj/item/clothing/suit/storage/hazardvest,
		),
		"rare" = list(
			/obj/item/clothing/under/rank/captain,
			/obj/item/clothing/under/rank/hos,
			/obj/item/clothing/under/rank/hop,
			/obj/item/clothing/under/rank/rd,
			/obj/item/clothing/under/rank/ce,
			/obj/item/clothing/under/rank/cmo,
			/obj/item/clothing/under/rank/warden,
			/obj/item/clothing/under/syndicate,
			/obj/item/clothing/under/syndicate/tacticool,
			/obj/item/clothing/head/lordadmiralhat,
			/obj/item/clothing/head/jesterhat,
			/obj/item/clothing/head/libertyhat,
			/obj/item/clothing/head/powdered_wig,
			/obj/item/clothing/head/helmet/tactical,
			/obj/item/clothing/head/hardhat/gold,
			/obj/item/clothing/shoes/jackboots,
			/obj/item/clothing/shoes/magboots,
			/obj/item/clothing/shoes/swat,
			/obj/item/clothing/gloves/swat,
			/obj/item/clothing/suit/armor/vest/security,
			/obj/item/clothing/suit/armor/bulletproof,
			/obj/item/clothing/suit/armor/laserproof,
			/obj/item/clothing/suit/armor/riot,
		),
		"very rare" = list(
			/obj/item/clothing/suit/captunic,
			/obj/item/clothing/head/captain,
			/obj/item/clothing/under/clownpiece,
			/obj/item/clothing/under/soviet,
			/obj/item/clothing/head/alien_antenna,
			/obj/item/clothing/head/devil_horns,
			/obj/item/clothing/suit/space/rig,
			/obj/item/clothing/head/helmet/space/rig,
			/obj/item/clothing/suit/space/ert,
			/obj/item/clothing/head/helmet/space/ert,
			/obj/item/clothing/suit/armor/plate_carrier,
			/obj/item/clothing/suit/armor/xcomarmor,
		)
	)

/datum/loot_table/combat
	loot = list(
		"common" = list(
			/obj/item/weapon/melee/classic_baton,
			/obj/item/weapon/melee/telebaton,
			/obj/item/weapon/bat,
			/obj/item/weapon/kitchen/utensil/knife/large/butch,
			/obj/item/weapon/kitchen/utensil/knife/large,
			/obj/item/weapon/hatchet,
			/obj/item/weapon/handcuffs,
			/obj/item/weapon/chainsaw,
			/obj/item/weapon/crowbar,
			/obj/item/weapon/fireaxe,
			/obj/item/weapon/melee/baton,
			/obj/item/weapon/cane,
			/obj/item/clothing/suit/armor/vest,
			/obj/item/clothing/head/helmet,
			/obj/item/weapon/shield/riot,
		),
		"uncommon" = list(
			/obj/item/weapon/claymore,
			/obj/item/weapon/katana,
			/obj/item/weapon/spear,
			/obj/item/weapon/pitchfork,
			/obj/item/weapon/rsscimmy,
			/obj/item/weapon/sword/shortsword,
			/obj/item/weapon/gun/energy/taser,
			/obj/item/weapon/gun/projectile/automatic/pistol,
			/obj/item/weapon/gun/projectile/revolver/detective,
			/obj/item/weapon/gun/energy/laser,
			/obj/item/weapon/gun/energy/gun,
			/obj/item/weapon/shield/energy,
			/obj/item/clothing/suit/armor/vest/security,
			/obj/item/clothing/suit/armor/vest/chainmail,
			/obj/item/clothing/head/helmet/tactical,
			/obj/item/clothing/gloves/knuckles,
		),
		"rare" = list(
			/obj/item/weapon/sword/scimitar,
			/obj/item/weapon/sword/gladius,
			/obj/item/weapon/sword/sabre,
			/obj/item/weapon/gun/energy/laser/cannon,
			/obj/item/weapon/gun/energy/ionrifle,
			/obj/item/weapon/gun/energy/plasma/pistol,
			/obj/item/weapon/gun/projectile/shotgun,
			/obj/item/weapon/gun/projectile/automatic/machine_pistol,
			/obj/item/weapon/gun/projectile/automatic/c20r,
			/obj/item/weapon/gun/energy/crossbow,
			/obj/item/weapon/gun/energy/smalldisintegrator,
			/obj/item/weapon/melee/energy/sword,
			/obj/item/weapon/melee/energy/hfmachete,
			/obj/item/weapon/shield/riot/tower,
			/obj/item/clothing/suit/armor/knight,
			/obj/item/clothing/suit/armor/riot,
			/obj/item/clothing/head/helmet/tactical/bulletproof,
			/obj/item/clothing/head/helmet/tactical/swat,
		),
		"very rare" = list(
			/obj/item/weapon/katana/hfrequency,
			/obj/item/weapon/armblade,
			/obj/item/weapon/caber,
			/obj/item/weapon/gun/energy/pulse_rifle,
			/obj/item/weapon/gun/energy/plasma/rifle,
			/obj/item/weapon/gun/energy/heavydisintegrator,
			/obj/item/weapon/gun/energy/advdisintegrator,
			/obj/item/weapon/gun/energy/gatling,
			/obj/item/weapon/gun/projectile/automatic/l6_saw,
			/obj/item/weapon/melee/energy/sword/dualsaber,
			/obj/item/weapon/melee/energy/hfmachete/bloodlust,
			/obj/item/clothing/suit/armor/laserproof,
			/obj/item/clothing/suit/armor/knight/rune,
			/obj/item/clothing/suit/space/rig/security,
			/obj/item/clothing/head/helmet/space/rig/security,
		)
	)

/datum/loot_table/decoration
	loot = list(
		"common" = list(
			/obj/item/mounted/poster,
			/obj/item/weapon/beach_ball,
			/obj/item/toy/plushie/monkey,
			/obj/item/toy/plushie/penguin,
			/obj/item/toy/plushie/ladybug,
			/obj/item/toy/plushie/parrot,
			/obj/item/toy/plushie/possum,
			/obj/item/toy/plushie/corgi,
			/obj/item/toy/plushie/cat,
			/obj/item/toy/plushie/mouse,
			/obj/item/toy/plushie/lizard,
			/obj/item/toy/plushie/spider,
			/obj/item/ornament,
			/obj/item/ornament/red,
			/obj/item/ornament/blue,
			/obj/item/ornament/green,
			/obj/item/ornament/teardrop,
			/obj/item/candle,
			/obj/item/weapon/bikehorn,
			/obj/item/mounted/frame/painting,
		),
		"uncommon" = list(
			/obj/item/mounted/frame/painting/blank,
			/obj/item/toy/plushie/peacekeeper,
			/obj/item/toy/plushie/orca,
			/obj/item/toy/plushie/kitten,
			/obj/item/toy/plushie/kitten/wizard,
			/obj/item/toy/plushie/fumo,
			/obj/item/toy/plushie/chicken,
			/obj/item/toy/plushie/bee,
			/obj/item/toy/plushie/shark,
			/obj/item/toy/plushie/alien,
			/obj/item/ornament/silver,
			/obj/item/ornament/gold,
			/obj/item/ornament/teardrop/silver,
			/obj/item/ornament/teardrop/gold,
			/obj/item/ornament/topper,
			/obj/item/weapon/storage/photo_album,
			/obj/structure/sign/goldstar,
			/obj/structure/sign/science,
			/obj/item/weapon/beach_ball/holoball,
			/obj/structure/easel,
		),
		"rare" = list(
			/obj/item/toy/plushie/narsie,
			/obj/item/toy/plushie/ratvar,
			/obj/item/toy/plushie/cthulhu,
			/obj/item/toy/plushie/fumo/touhou/reimu,
			/obj/item/toy/plushie/fumo/touhou/marisa,
			/obj/item/toy/plushie/fumo/touhou/sakuya,
			/obj/item/toy/plushie/fumo/touhou/yukari,
			/obj/item/toy/plushie/chicken/pomf,
			/obj/structure/sign/goldenplaque,
			/obj/structure/sign/kiddieplaque,
			/obj/structure/sign/atmosplaque,
			/obj/item/weapon/banhammer,
			/obj/item/mounted/frame/painting/custom,
			/obj/item/mounted/frame/painting/custom/large,
		),
		"very rare" = list(
			/obj/item/weapon/statue,
			/obj/item/toy/plushie/cthulhu,
			/obj/structure/painting/narsie,
			/obj/structure/painting/random,
		)
	)

/datum/loot_table/engineering
	loot = list(
		"common" = list(
			/obj/item/tool/wrench,
			/obj/item/tool/screwdriver,
			/obj/item/tool/wirecutters,
			/obj/item/tool/crowbar,
			/obj/item/tool/weldingtool,
			/obj/item/tool/hammer,
			/obj/item/tool/pickaxe,
			/obj/item/tool/shovel,
			/obj/item/device/multitool,
			/obj/item/device/analyzer,
			/obj/item/device/t_scanner,
			/obj/item/device/flashlight,
			/obj/item/device/flashlight/lantern,
			/obj/item/stack/cable_coil/random,
			/obj/item/stack/sheet/metal,
			/obj/item/stack/sheet/glass/glass,
			/obj/item/weapon/table_parts,
			/obj/item/weapon/rack_parts,
			/obj/item/weapon/tank/air,
			/obj/item/weapon/tank/oxygen,
		),
		"uncommon" = list(
			/obj/item/tool/wrench/socket,
			/obj/item/tool/weldingtool/hugetank,
			/obj/item/tool/solder,
			/obj/item/tool/pickaxe/drill,
			/obj/item/tool/pickaxe/silver,
			/obj/item/device/silicate_sprayer,
			/obj/item/device/flashlight/heavy,
			/obj/item/device/device_analyzer,
			/obj/item/stack/sheet/plasteel,
			/obj/item/stack/sheet/glass/rglass,
			/obj/item/stack/sheet/mineral/uranium,
			/obj/item/stack/sheet/mineral/silver,
			/obj/item/weapon/table_parts/reinforced,
			/obj/item/weapon/table_parts/wood,
			/obj/item/weapon/table_parts/glass,
			/obj/item/weapon/rcl,
			/obj/item/weapon/tank/nitrogen,
			/obj/item/weapon/tank/plasma,
		),
		"rare" = list(
			/obj/item/tool/weldingtool/experimental,
			/obj/item/tool/solder/screw,
			/obj/item/tool/pickaxe/gold,
			/obj/item/tool/pickaxe/diamond,
			/obj/item/tool/pickaxe/plasmacutter,
			/obj/item/weapon/switchtool/engineering,
			/obj/item/device/flashlight/seclite,
			/obj/item/stack/sheet/glass/plasmaglass,
			/obj/item/stack/sheet/glass/plasmarglass,
			/obj/item/stack/sheet/mineral/gold,
			/obj/item/stack/sheet/mineral/diamond,
			/obj/item/stack/sheet/mineral/plasma,
			/obj/item/weapon/table_parts/glass/plasma,
			/obj/item/weapon/table_parts/clockwork,
			/obj/item/device/material_synth,
			/obj/item/weapon/tank/emergency_oxygen,
		),
		"very rare" = list(
			/obj/item/weapon/switchtool/holo,
			/obj/item/device/rcd,
			/obj/item/device/rcd/rpd,
			/obj/item/tool/pickaxe/drill/jackhammer,
		)
	)

/datum/loot_table/entertainment
	loot = list(
		"common" = list(
			/obj/item/toy/cards/deck,
			/obj/item/toy/dice,
			/obj/item/toy/dice/d20,
			/obj/item/toy/gun,
			/obj/item/toy/sword,
			/obj/item/toy/katana,
			/obj/item/toy/crossbow,
			/obj/item/toy/waterballoon,
			/obj/item/toy/blink,
			/obj/item/toy/spinningtoy,
			/obj/item/toy/minimeteor,
			/obj/item/toy/bomb,
			/obj/item/weapon/storage/fancy/crayons,
			/obj/item/device/instrument/violin,
			/obj/item/device/instrument/guitar,
			/obj/item/device/instrument/recorder,
			/obj/item/device/maracas,
		),
		"uncommon" = list(
			/obj/item/toy/cards/une,
			/obj/item/toy/gasha,
			/obj/item/toy/snappop,
			/obj/item/toy/balloon/long,
			/obj/item/toy/foamblade,
			/obj/item/toy/boomerang,
			/obj/item/toy/syndicateballoon/ntballoon,
			/obj/item/device/roganbot,
			/obj/item/weapon/winter_gift/dorkcube,
			/obj/item/device/handtv,
			/obj/item/weapon/storage/box/actionfigure,
			/obj/item/weapon/storage/box/mechfigures,
			/obj/item/device/instrument/saxophone,
			/obj/item/device/instrument/trombone,
			/obj/item/device/instrument/accordion,
			/obj/item/device/instrument/glockenspiel,
			/obj/item/device/instrument/drum,
		),
		"rare" = list(
			/obj/item/toy/prize/deathripley,
			/obj/item/toy/gasha/alium,
			/obj/item/toy/gasha/pomf,
			/obj/item/toy/gasha/engi,
			/obj/item/toy/gasha/atmos,
			/obj/item/toy/gasha/sec,
			/obj/item/toy/gasha/plasman,
			/obj/item/toy/gasha/shard,
			/obj/item/device/whisperphone,
			/obj/item/weapon/storage/box/syndicatefake/space,
			/obj/item/device/instrument/drum/drum_makeshift/bongos,
			/obj/machinery/computer/arcade,
			/obj/machinery/claw_machine,
		),
		"very rare" = list(
			/obj/item/device/wormhole_jaunter,
			/obj/item/device/paicard,
			/obj/machinery/computer/arcade/haunted,
		)
	)

/datum/loot_table/exotic
	loot = list(
		"common" = list(
			/obj/item/device/assembly/mousetrap,
			/obj/item/beacon,
			/obj/item/weapon/caution,
			/obj/item/weapon/caution/cone,
			/obj/item/inflatable/wall,
			/obj/item/inflatable/door,
			/obj/item/weapon/soap,
			/obj/item/weapon/beartrap,
			/obj/item/weapon/card/data/clown,
			/obj/item/device/assembly/igniter,
			/obj/item/device/assembly/timer,
			/obj/item/device/assembly/prox_sensor,
		),
		"uncommon" = list(
			/obj/item/clothing/suit/space/vox/civ,
			/obj/item/clothing/head/helmet/space/vox/civ,
			/obj/item/clothing/suit/space/vox/stealth,
			/obj/item/clothing/head/helmet/space/vox/stealth,
			/obj/item/clothing/suit/space/unathi,
			/obj/item/clothing/head/helmet/space/unathi,
			/obj/item/weapon/reagent_containers/food/snacks/artifact,
			/obj/item/weapon/storage/box/large/xa_excasuit,
			/obj/item/weapon/storage/box/large/xa_anomsuit,
			/obj/item/weapon/storage/box/large/xa_atomicsuit,
			/obj/item/weapon/bikehorn/rubberducky,
			/obj/item/device/assembly/signaler,
			/obj/item/device/assembly/voice,
			/obj/item/device/assembly/flashstrobe,
		),
		"rare" = list(
			/obj/item/clothing/suit/space/vox/civ/trader/carapace,
			/obj/item/clothing/head/helmet/space/vox/civ/trader/carapace,
			/obj/item/clothing/suit/space/vox/civ/trader/medic,
			/obj/item/clothing/suit/space/anomaly,
			/obj/item/clothing/head/helmet/space/anomaly,
			/obj/item/clothing/suit/space/rig/grey,
			/obj/item/clothing/head/helmet/space/rig/grey,
			/obj/item/clothing/suit/armor/mothership,
			/obj/item/clothing/suit/armor/mothership/explorer,
			/obj/item/weapon/switchtool/alien,
			/obj/item/device/alien_scanner,
			/obj/item/device/assembly/grenade,
		),
		"very rare" = list(
			/obj/item/device/jump_charge,
			/obj/item/device/timeline_eraser,
			/obj/item/device/chronocapture,
			/obj/item/clothing/suit/space/rig/grey/leader,
			/obj/item/clothing/head/helmet/space/rig/grey/leader,
			/obj/item/clothing/suit/space/unathi/breacher,
			/obj/item/clothing/head/helmet/space/unathi/breacher,
			/obj/item/clothing/suit/armor/mothership_heavy,
			/obj/item/weapon/gun/energy/smalldisintegrator,
			/obj/item/weapon/gun/energy/heavydisintegrator,
		)
	)

/datum/loot_table/food_or_drink
	loot = list(
		"common" = list(
			/obj/item/weapon/reagent_containers/food/drinks/soda_cans/cola,
			/obj/item/weapon/reagent_containers/food/drinks/soda_cans/space_mountain_wind,
			/obj/item/weapon/reagent_containers/food/drinks/soda_cans/dr_gibb,
			/obj/item/weapon/reagent_containers/food/drinks/plastic/water,
			/obj/item/weapon/reagent_containers/food/drinks/plastic/water/small,
			/obj/item/weapon/reagent_containers/food/drinks/beer,
			/obj/item/weapon/reagent_containers/food/drinks/coffee,
			/obj/item/weapon/reagent_containers/food/drinks/mug,
			/obj/item/weapon/reagent_containers/food/drinks/mug/tea,
			/obj/item/weapon/reagent_containers/food/drinks/bottle/milk,
			/obj/item/weapon/reagent_containers/food/condiment/small/hotsauce,
			/obj/item/weapon/reagent_containers/food/condiment/small/ketchup,
			/obj/item/weapon/reagent_containers/food/condiment/small/mayo,
			/obj/item/weapon/reagent_containers/food/condiment/small/salt,
			/obj/item/weapon/reagent_containers/food/condiment/small/pepper,
			/obj/item/weapon/kitchen/utensil/spork/plastic,
			/obj/item/weapon/kitchen/utensil/fork,
			/obj/item/weapon/kitchen/utensil/knife,
			/obj/item/weapon/kitchen/utensil/spoon,
		),
		"uncommon" = list(
			/obj/item/weapon/reagent_containers/food/drinks/soda_cans/zam_sulphuricsplash,
			/obj/item/weapon/reagent_containers/food/drinks/soda_cans/zam_formicfizz,
			/obj/item/weapon/reagent_containers/food/drinks/soda_cans/zam_trustytea,
			/obj/item/weapon/reagent_containers/food/drinks/soda_cans/zam_tannicthunder,
			/obj/item/weapon/reagent_containers/food/drinks/bottle/wine,
			/obj/item/weapon/reagent_containers/food/drinks/bottle/rum,
			/obj/item/weapon/reagent_containers/food/drinks/bottle/whiskey,
			/obj/item/weapon/reagent_containers/food/drinks/bottle/vodka,
			/obj/item/weapon/reagent_containers/food/drinks/bottle/gin,
			/obj/item/weapon/reagent_containers/food/condiment/small/zamspices,
			/obj/item/weapon/reagent_containers/food/condiment/small/zammild,
			/obj/item/weapon/kitchen/utensil/spork/plastic/teflon,
			/obj/item/weapon/storage/fancy/donut_box,
			/obj/item/pizzabox/margherita,
			/obj/item/pizzabox/meat,
			/obj/item/weapon/reagent_containers/food/snacks/candy,
			/obj/item/weapon/reagent_containers/food/snacks/mre,
			/obj/item/weapon/kitchen/tray,
		),
		"rare" = list(
			/obj/item/weapon/reagent_containers/food/condiment/small/zamspicytoxin,
			/obj/item/pizzabox/vegetable,
			/obj/item/pizzabox/mushroom,
			/obj/item/weapon/reagent_containers/food/drinks/bottle/champagne,
			/obj/item/weapon/reagent_containers/food/drinks/bottle/absinthe,
			/obj/item/weapon/reagent_containers/food/drinks/bottle/cognac,
			/obj/item/weapon/reagent_containers/food/snacks/caviar,
			/obj/item/weapon/reagent_containers/food/snacks/truffle,
			/obj/item/weapon/storage/fancy/cigarettes,
		),
		"very rare" = list(
			/obj/item/weapon/kitchen/canopener,
			/obj/item/weapon/reagent_containers/food/drinks/bottle/patron,
			/obj/item/weapon/reagent_containers/food/drinks/bottle/goldschlager,
		)
	)

/datum/loot_table/medical
	loot = list(
		"common" = list(
			/obj/item/tool/scalpel,
			/obj/item/tool/circular_saw,
			/obj/item/tool/surgicaldrill,
			/obj/item/tool/retractor,
			/obj/item/tool/hemostat,
			/obj/item/tool/cautery,
			/obj/item/tool/bonesetter,
			/obj/item/tool/FixOVein,
			/obj/item/tool/bonegel,
			/obj/item/stack/medical/bruise_pack,
			/obj/item/stack/medical/ointment,
			/obj/item/stack/medical/splint,
			/obj/item/weapon/reagent_containers/syringe,
			/obj/item/weapon/reagent_containers/pill/antitox,
			/obj/item/weapon/reagent_containers/pill/bicaridine,
			/obj/item/weapon/reagent_containers/pill/kelotane,
			/obj/item/weapon/reagent_containers/pill/tramadol,
			/obj/item/device/healthanalyzer,
		),
		"uncommon" = list(
			/obj/item/tool/scalpel/laser,
			/obj/item/tool/cautery/laser,
			/obj/item/tool/hemostat/pico,
			/obj/item/tool/retractor/manager,
			/obj/item/tool/bonesetter/bone_mender,
			/obj/item/tool/FixOVein/clot,
			/obj/item/stack/medical/advanced/bruise_pack,
			/obj/item/stack/medical/advanced/ointment,
			/obj/item/weapon/switchtool/surgery,
			/obj/item/weapon/reagent_containers/pill/dexalin,
			/obj/item/weapon/reagent_containers/pill/dexalin_plus,
			/obj/item/weapon/reagent_containers/pill/dermaline,
			/obj/item/weapon/reagent_containers/pill/dyroxadone,
			/obj/item/weapon/reagent_containers/pill/inaprovaline,
			/obj/item/device/antibody_scanner,
			/obj/item/weapon/storage/firstaid,
			/obj/item/weapon/storage/firstaid/trauma,
			/obj/item/weapon/storage/firstaid/fire,
			/obj/item/weapon/storage/firstaid/regular,
		),
		"rare" = list(
			/obj/item/tool/scalpel/laser/tier2,
			/obj/item/tool/circular_saw/plasmasaw,
			/obj/item/tool/surgicaldrill/diamond,
			/obj/item/tool/cautery/laser/tier2,
			/obj/item/weapon/switchtool/surgery/maxed,
			/obj/item/weapon/reagent_containers/pill/omnizine,
			/obj/item/weapon/reagent_containers/pill/hyperzine,
			/obj/item/weapon/reagent_containers/pill/ritalin,
			/obj/item/weapon/storage/firstaid/toxin,
			/obj/item/weapon/storage/firstaid/o2,
			/obj/item/weapon/storage/firstaid/radiation,
			/obj/item/device/nanoblood_injector,
			/obj/item/device/device_analyzer/healthanalyzer,
		),
		"very rare" = list(
			/obj/item/roller/surgery,
			/obj/item/weapon/reagent_containers/pill/sleeptoxin,
			/obj/item/weapon/reagent_containers/pill/zombiepowder,
			/obj/item/weapon/storage/firstaid/combat,
		)
	)

/datum/loot_table/module
	loot = list(
		"common" = list(
			/obj/item/weapon/aiModule/core/asimov,
			/obj/item/weapon/aiModule/core/corp,
			/obj/item/weapon/aiModule/core/nanotrasen,
			/obj/item/weapon/aiModule/core/robocop,
			/obj/item/weapon/aiModule/freeform/core,
			/obj/item/weapon/aiModule/keeper,
			/obj/item/weapon/aiModule/purge,
		),
		"uncommon" = list(
			/obj/item/weapon/aiModule/core/hogan,
			/obj/item/weapon/aiModule/core/lazymov,
			/obj/item/weapon/aiModule/core/paladin,
			/obj/item/weapon/aiModule/core/tyrant,
			/obj/item/weapon/aiModule/randomize,
			/obj/item/weapon/aiModule/standard/protectStation,
			/obj/item/weapon/aiModule/standard/teleporterOffline,
		),
		"rare" = list(
			/obj/item/weapon/aiModule/core/antimov,
			/obj/item/weapon/aiModule/standard/oxygen,
			/obj/item/weapon/aiModule/standard/quarantine,
		),
		"very rare" = list(
			/obj/item/weapon/aiModule/freeform/syndicate,
			/obj/item/weapon/aiModule/targetted/safeguard,
			/obj/item/weapon/aiModule/targetted/oneHuman,
		)
	)

/datum/loot_table/structure
	loot = list(
		"common" = list(
			/obj/structure/closet,
			/obj/structure/closet/crate,
			/obj/structure/table,
			/obj/structure/rack,
			/obj/structure/bed/chair,
			/obj/structure/bed/chair/plastic/plastic_chair,
			/obj/structure/flora/pottedplant,
			/obj/machinery/vending/snack,
			/obj/machinery/vending/cola,
			/obj/machinery/vending/cigarette,
			/obj/machinery/vending/coffee,
			/obj/machinery/photocopier,
		),
		"uncommon" = list(
			/obj/structure/closet/acloset,
			/obj/structure/closet/crate/basic,
			/obj/structure/table/woodentable,
			/obj/structure/table/reinforced,
			/obj/structure/bed/chair/comfy,
			/obj/machinery/vending/wallmed2,
			/obj/machinery/vending/boozeomat,
			/obj/machinery/vending/dinnerware,
			/obj/machinery/vending/getmore,
			/obj/machinery/vending/hatdispenser,
			/obj/machinery/autolathe,
			/obj/machinery/r_n_d/fabricator/circuit_imprinter,
		),
		"rare" = list(
			/obj/structure/table/glass,
			/obj/structure/table/glass/plasma,
			/obj/structure/table/reinforced/clockwork,
			/obj/structure/bed/chair/office/light,
			/obj/structure/bed/chair/office/dark,
			/obj/machinery/vending/security,
			/obj/machinery/vending/medical,
			/obj/machinery/vending/engineering,
			/obj/machinery/vending/robotics,
			/obj/machinery/vending/hydronutrients,
			/obj/machinery/r_n_d/fabricator/protolathe,
			/obj/machinery/r_n_d/fabricator/mech,
		),
		"very rare" = list(
			/obj/structure/bed/chair/e_chair,
			/obj/machinery/vending/telecomms,
			/obj/machinery/vending/team_security,
			/obj/machinery/atm,
			/obj/machinery/keyfab,
			/obj/machinery/pdapainter,
		)
	)

/datum/loot_table/trash
	loot = list(
		"common" = list(
			/obj/item/trash/bustanuts,
			/obj/item/trash/raisins,
			/obj/item/trash/candy,
			/obj/item/trash/chips,
			/obj/item/trash/popcorn,
			/obj/item/trash/sosjerky,
			/obj/item/trash/syndi_cakes,
			/obj/item/trash/soda_cans,
			/obj/item/trash/waffles,
			/obj/item/trash/snack_bowl,
			/obj/item/trash/tray,
			/obj/item/trash/packet/ketchup,
			/obj/item/trash/packet/mayo,
			/obj/item/trash/packet/soysauce,
		),
		"uncommon" = list(
			/obj/item/trash/chips/cheesie,
			/obj/item/trash/chips/donitos,
			/obj/item/trash/chips/danitos,
			/obj/item/trash/dangles,
			/obj/item/trash/monkey_bowl,
			/obj/item/trash/pistachios,
			/obj/item/trash/semki,
			/obj/item/trash/used_tray,
			/obj/item/trash/zam_notraisins,
			/obj/item/trash/egg,
			/obj/item/trash/liquidfood,
		),
		"rare" = list(
			/obj/item/trash/chicken_bucket,
			/obj/item/trash/fries_cone,
			/obj/item/trash/fries_punet,
			/obj/item/trash/candle,
			/obj/item/trash/mannequin,
			/obj/item/trash/byond_box,
			/obj/item/trash/slag,
		),
		"very rare" = list(
			/obj/item/trash/mannequin/cult,
			/obj/item/trash/mannequin/large,
			/obj/item/trash/broken_ashtray,
			/obj/item/trash/broken_ashtray/bronze,
			/obj/item/trash/broken_ashtray/glass,
		)
	)
