#define COLOR_DARKMODE_BACKGROUND "#282828"
#define COLOR_DARKMODE_DARKBACKGROUND "#1d2021"
#define COLOR_DARKMODE_BUTTONBACKGROUND "#32302f"
#define COLOR_DARKMODE_TEXT "#a4bad6"

#define COLOR_WHITEMODE_BACKGROUND "none"
#define COLOR_WHITEMODE_INFOBACKGROUND "#FFFFFF"
#define COLOR_WHITEMODE_TEXT "#000000"
