#define COMMON "Common"
#define SECURITY_COMM "Security" //Due to a define conflict with Economy/Economy.dm, this is different from the rest
#define ENGINEERING "Engineering"
#define COMMAND "Command"
#define MEDICAL "Medical"
#define SCIENCE "Science"
#define SERVICE "Service"
#define CARGO "Supply"
#define DEATHSQUAD_COMM "Deathsquad"
#define RESPONSE "Responders"
#define REV_COMM "Revolutionaries"
#define AIPRIVATE "AI Private"
#define DJ "DJ"
#define SYND "Syndicate"
#define RAIDER "Vox Raiders"
#define BUG "Radio Bug"

//Communication prefixes to communicate on these radio freqs. So far only used for detecting which frequency
//belongs to what prefix, showing it off in the radio headset.
//These don't actually determine which prefix belongs to what, it's just a reference point
#define COMMON_PREFIX "o"
#define SECURITY_PREFIX "s"
#define ENGINEERING_PREFIX "e"
#define COMMAND_PREFIX "c"
#define MEDICAL_PREFIX "m"
#define SCIENCE_PREFIX "n"
#define SERVICE_PREFIX "d"
#define SUPPLY_PREFIX "u"
#define DEATHSQUAD_PREFIX "0"
#define RESPONSE_PREFIX "-"
#define AIPRIVATE_PREFIX "p"
#define SYNDICATE_PREFIX "t"

var/list/freq_text = list(COMMON,SECURITY_COMM,ENGINEERING,COMMAND,MEDICAL,SCIENCE,SERVICE,CARGO,DEATHSQUAD_COMM,RESPONSE,AIPRIVATE,DJ,REV_COMM, SYND, RAIDER, BUG)
var/list/freqs = list() //Generated by generate_radio_frequencies, in more_init_stuff.dm

#define DSQUAD_FREQ freqs[DEATHSQUAD_COMM]
#define RESPONSE_FREQ freqs[RESPONSE]
#define AIPRIV_FREQ freqs[AIPRIVATE]
#define DJ_FREQ freqs[DJ]
#define COMMON_FREQ freqs[COMMON]

#define COMM_FREQ freqs[COMMAND]
#define REV_FREQ freqs[REV_COMM]
#define SYND_FREQ freqs[SYND]
#define RAID_FREQ freqs[RAIDER]
#define BUG_FREQ freqs[BUG]

#define SEC_FREQ freqs[SECURITY_COMM]
#define ENG_FREQ freqs[ENGINEERING]
#define SCI_FREQ freqs[SCIENCE]
#define MED_FREQ freqs[MEDICAL]
#define SUP_FREQ freqs[CARGO]
#define SER_FREQ freqs[SERVICE]

var/list/freqtospan = list()
var/list/radiochannels = list()
var/list/radiochannelsreverse = list()

//Only the channels that someone in the main station should have access to normally.
var/list/stationchannels = list()

//For custom stuff
var/list/freqtocolor = list()
