//Useful for making time-limited things.

#define NEW_YEARS_DAY "New Year's Day"
#define GROUNDHOG_DAY "Groundhog Day"
#define VALENTINES_DAY "Valentine's Day"
#define RANDOM_ACTS_OF_KINDNESS_DAY "Random Acts of Kindness Day"
#define PI_DAY "Pi Day"
#define ST_PATRICKS_DAY "St. Patrick's Day"
#define EASTER "Easter"
#define APRIL_FOOLS_DAY "April Fool's Day"
#define AUTISM_AWARENESS_DAY "Autism Awareness Day"
#define FOUR_TWENTY "Four-Twenty"
#define EARTH_DAY "Earth Day"
#define LABOUR_DAY "Labour Day"
#define FIREFIGHTERS_DAY "FireFighter's Day"
#define OWL_AND_PUSSYCAT_DAY "Owl and Pussycat Day"
#define INTERNATIONAL_PICNIC_DAY "International Picnic Day"
#define SUMMER_SOLSTICE "Summer Solstice"
#define DOCTORS_DAY "Doctor's Day"
#define UFO_DAY "UFO Day"
#define WRITERS_DAY "Writer's Day"
#define FRIENDSHIP_DAY "Friendship Day"
#define BEER_DAY "Beer Day"
#define TALK_LIKE_A_PIRATE_DAY "Talk-Like-a-Pirate Day"
#define STUPID_QUESTIONS_DAY "Stupid-Questions Day"
#define ANIMALS_DAY "Animal's Day"
#define SMILING_DAY "Smiling Day"
#define BOSS_DAY "Boss' Day"
#define HALLOWEEN "Halloween"
#define VEGAN_DAY "Vegan Day"
#define KINDNESS_DAY "Kindness Day"
#define FLOWERS_DAY "Flowers Day"
#define SAYING_HELLO_DAY "Saying-'Hello' Day"
#define HUMAN_RIGHTS_DAY "Human-Rights Day"
#define MONKEY_DAY "Monkey Day"
#define END_OF_THE_WORLD "End of the World"
#define ORGASMING_DAY "Orgasming Day"
#define XMAS_EVE "Christmas Eve"
#define XMAS "Christmas"
#define BOXING_DAY "Boxing Day"
#define NEW_YEARS_EVE "New Year's Eve"
#define FRIDAY_THE_13TH "Friday the 13th"