#define EMBED_THROWING_SPEED 20

#define MOB_RUN_TALLY 1
#define MOB_WALK_TALLY 4

#define NO_SLOWDOWN 1

#define HARDSUIT_SLOWDOWN_LOW 1.3
#define HARDSUIT_SLOWDOWN_MED 1.45
#define HARDSUIT_SLOWDOWN_HIGH 1.6
#define HARDSUIT_SLOWDOWN_BULKY 2

#define NO_SHOES_SLOWDOWN 1.4
#define MISC_SHOE_SLOWDOWN 1.2
#define MAGBOOTS_SLOWDOWN_LOW 1.2 //CE's magboots - could possibly be changed to NO_SLOWDOWN
#define MAGBOOTS_SLOWDOWN_HIGH 2
#define SHACKLE_SHOES_SLOWDOWN 15

#define MINIGUN_SLOWDOWN_NONWIELDED 1.2
#define MINIGUN_SLOWDOWN_WIELDED 8
