#define INVISIBLESPRAY "invisiblespray"
#define ETHEREAL "ethereal"
#define CLOAKINGCLOAK "cloakingcloak"
#define INVISIBLEPOTION "invisiblepotion"
#define TRANSPARENCYPOTION "transparencypotion"
#define HORROR "horror"