#define SYRINGE_DRAW 0
#define SYRINGE_INJECT 1
#define SYRINGE_BROKEN 2

#define INJECTION_BODY 0
#define INJECTION_SUIT_PORT 1

#define INJECTION_RESULT_FAIL 0
#define INJECTION_RESULT_SUCCESS 1
#define INJECTION_RESULT_SUCCESS_BUT_SKIP_REAGENT_TRANSFER 2
