#define TURF_DRY 0
#define TURF_WET_WATER 1
#define TURF_WET_LUBE 2
#define TURF_WET_ICE 3

#define TURF_CONTAINS_REGULAR_ROCKERNAUT 1
#define TURF_CONTAINS_BOSS_ROCKERNAUT 2

#define SLIP_HAS_MAGBOOTS -1 // Magbooties !


#define MINE_DIFFICULTY_NORM 1
#define MINE_DIFFICULTY_TOUGH 3
#define MINE_DIFFICULTY_DENSE 5
#define MINE_DIFFICULTY_GLHF 9