/obj/item/stack/sheet/metal/bigstack/New()
	..()
	getFromPool(/obj/item/stack/sheet/metal, loc, 20)
	qdel(src)
/obj/item/stack/sheet/glass/glass/bigstack/New()
	..()
	getFromPool(/obj/item/stack/sheet/glass/glass, loc, 20)
	qdel(src)
/obj/item/stack/sheet/glass/plasmaglass/bigstack/New()
	..()
	getFromPool(/obj/item/stack/sheet/glass/plasmaglass, loc, 20)
	qdel(src)
/obj/item/stack/sheet/plasteel/bigstack/New()
	..()
	getFromPool(/obj/item/stack/sheet/plasteel, loc, 20)
	qdel(src)
/obj/item/stack/sheet/wood/bigstack/New()
	..()
	getFromPool(/obj/item/stack/sheet/wood, loc, 20)
	qdel(src)
/obj/item/stack/tile/carpet/bigstack/New()
	..()
	getFromPool(/obj/item/stack/tile/carpet, loc, 20)
	qdel(src)
/obj/item/stack/tile/arcade/bigstack/New()
	..()
	getFromPool(/obj/item/stack/tile/arcade, loc, 20)
	qdel(src)
/obj/item/stack/sheet/mineral/plastic/bigstack/New()
	..()
	getFromPool(/obj/item/stack/sheet/mineral/plastic, loc, 20)
	qdel(src)
/obj/item/stack/sheet/brass/bigstack/New()
	..()
	getFromPool(/obj/item/stack/sheet/brass, loc, 50)
	qdel(src)
/obj/item/stack/sheet/ralloy/bigstack/New()
	..()
	getFromPool(/obj/item/stack/sheet/ralloy, loc, 50)
	qdel(src)