/obj/item/stack/sheet/metal/bigstack/New()
	..()
	new /obj/item/stack/sheet/metal(loc, 20)
	qdel(src)
/obj/item/stack/sheet/glass/glass/bigstack/New()
	..()
	new /obj/item/stack/sheet/glass/glass(loc, 20)
	qdel(src)
/obj/item/stack/sheet/glass/plasmaglass/bigstack/New()
	..()
	new /obj/item/stack/sheet/glass/plasmaglass(loc, 20)
	qdel(src)
/obj/item/stack/sheet/plasteel/bigstack/New()
	..()
	new /obj/item/stack/sheet/plasteel(loc, 20)
	qdel(src)
/obj/item/stack/sheet/wood/bigstack/New()
	..()
	new /obj/item/stack/sheet/wood(loc, 20)
	qdel(src)
/obj/item/stack/sheet/wood/biggerstack/New()
	..()
	new /obj/item/stack/sheet/wood(loc, 50)
	qdel(src)
/obj/item/stack/tile/carpet/bigstack/New()
	..()
	new /obj/item/stack/tile/carpet(loc, 20)
	qdel(src)
/obj/item/stack/tile/arcade/bigstack/New()
	..()
	new /obj/item/stack/tile/arcade(loc, 20)
	qdel(src)
/obj/item/stack/sheet/mineral/plastic/bigstack/New()
	..()
	new /obj/item/stack/sheet/mineral/plastic(loc, 20)
	qdel(src)
/obj/item/stack/sheet/brass/bigstack/New()
	..()
	new /obj/item/stack/sheet/brass(loc, 50)
	qdel(src)
/obj/item/stack/sheet/ralloy/bigstack/New()
	..()
	new /obj/item/stack/sheet/ralloy(loc, 50)
	qdel(src)
/obj/item/stack/sheet/mineral/brick/bigstack
	name = "stack of bricks"
/obj/item/stack/sheet/mineral/brick/bigstack/New()
	..()
	new /obj/item/stack/sheet/mineral/brick(loc,20)
	qdel(src)
/obj/item/stack/sheet/cloth/bigstack/New()
	..()
	new /obj/item/stack/sheet/cloth(loc, 20)
	qdel(src)
/obj/item/stack/sheet/cloth/biggerstack/New()
	..()
	new /obj/item/stack/sheet/cloth(loc, 50)
	qdel(src)

/obj/item/stack/sheet/wax/times_two/New()
	..()
	new /obj/item/stack/sheet/wax(get_turf(src), 2, color)
	qdel(src)
/obj/item/stack/sheet/wax/times_three/New()
	..()
	new /obj/item/stack/sheet/wax(get_turf(src), 3, color)
	qdel(src)
/obj/item/stack/sheet/wax/times_four/New()
	..()
	new /obj/item/stack/sheet/wax(get_turf(src), 4, color)
	qdel(src)
/obj/item/stack/sheet/wax/times_ten/New()
	..()
	new /obj/item/stack/sheet/wax(get_turf(src), 10, color)
	qdel(src)
/obj/item/stack/sheet/wax/bigstack/New()
	..()
	new /obj/item/stack/sheet/wax(get_turf(src), 20, color)
	qdel(src)
/obj/item/stack/sheet/wax/biggerstack/New()
	..()
	new /obj/item/stack/sheet/wax(get_turf(src), 50, color)
	qdel(src)
