/obj/item/stack/sheet/metal/bigstack/New()
	..()
	new /obj/item/stack/sheet/metal(loc, 20)
	qdel(src)
/obj/item/stack/sheet/glass/glass/bigstack/New()
	..()
	new /obj/item/stack/sheet/glass/glass(loc, 20)
	qdel(src)
/obj/item/stack/sheet/glass/plasmaglass/bigstack/New()
	..()
	new /obj/item/stack/sheet/glass/plasmaglass(loc, 20)
	qdel(src)
/obj/item/stack/sheet/plasteel/bigstack/New()
	..()
	new /obj/item/stack/sheet/plasteel(loc, 20)
	qdel(src)
/obj/item/stack/sheet/wood/bigstack/New()
	..()
	new /obj/item/stack/sheet/wood(loc, 20)
	qdel(src)
/obj/item/stack/tile/carpet/bigstack/New()
	..()
	new /obj/item/stack/tile/carpet(loc, 20)
	qdel(src)
/obj/item/stack/tile/arcade/bigstack/New()
	..()
	new /obj/item/stack/tile/arcade(loc, 20)
	qdel(src)
/obj/item/stack/sheet/mineral/plastic/bigstack/New()
	..()
	new /obj/item/stack/sheet/mineral/plastic(loc, 20)
	qdel(src)
/obj/item/stack/sheet/brass/bigstack/New()
	..()
	new /obj/item/stack/sheet/brass(loc, 50)
	qdel(src)
/obj/item/stack/sheet/ralloy/bigstack/New()
	..()
	new /obj/item/stack/sheet/ralloy(loc, 50)
	qdel(src)
/obj/item/stack/sheet/mineral/brick/bigstack
	name = "stack of bricks"
/obj/item/stack/sheet/mineral/brick/bigstack/New()
	..()
	new /obj/item/stack/sheet/mineral/brick(loc,20)
	qdel(src)