/proc/captain_announce(var/text)
	to_chat(world, "<h1 class='alert'>Priority Announcement</h1>")
	to_chat(world, "<span class='alert'>[html_encode(text)]</span>")
	to_chat(world, "<br>")
	for(var/mob/M in player_list)
		if(!istype(M,/mob/new_player) && M.client)
			M << sound('sound/vox/_doop.wav')
