#define SOFT_DM "digital messenger"
#define SOFT_CM "crew manifest"
#define SOFT_FL "flashlight"
#define SOFT_RT "redundant threading"
#define SOFT_RS "remote signaller"
#define SOFT_WJ "wirejack"
#define SOFT_CS "chem synth"
#define SOFT_FS "food synth"
#define SOFT_UT "universal translator"
#define SOFT_MS "medical supplement"
#define SOFT_SS "security supplement"
#define SOFT_AS "atmosphere sensor"
#define SOFT_PS "pai positioning system"