//For lists of words to be used with viruses.
var/global/list/virus_opposite_word_list

/datum/disease2/proc/initialize_word_lists()
	virus_opposite_word_list = list("to"		=	"from",				//1
									"and"		=	"not",				//2
									"in"		=	"out",				//3
									"that"		=	"this",				//4
									"I"			=	"you",				//5
									"on"		=	"off",				//6
									"with"		=	"without",			//7
									"he"		=	"she",				//8
									"we"		=	"they",				//9
									"his"		=	"her",				//10
									"will"		=	"won't",			//11
									"my"		=	"your",				//12
									"mine"		=	"yours",			//13
									"one"		=	"two",				//14
									"all"		=	"none",				//15
									"would"		=	"wouldn't",			//16
									"there"		=	"here",				//17
									"their"		=	"our",				//18
									"what"		=	"who",				//19
									"up"		=	"down",				//20
									"go"		=	"come",				//21
									"when"		=	"where",			//22
									"no"		=	"yes",				//23
									"him"		=	"her",				//24
									"take"		=	"give",				//25
									"into"		=	"out of",			//26
									"good"		=	"bad",				//27
									"some"		=	"none",				//28
									"could"		=	"couldn't",			//29
									"them"		=	"us",				//30
									"see"		=	"hear",				//31
									"now"		=	"later",			//32
									"look"		=	"listen",			//33
									"over"		=	"under",			//34
									"think"		=	"know",				//35
									"back"		=	"front",			//36
									"after"		=	"before",			//37
									"how"		=	"why",				//38
									"first"		=	"last",				//39
									"new"		=	"old",				//40
									"most"		=	"least",			//41
									"help"		=	"kill",				//42
									"hurt"		=	"heal",				//43
									"left"		=	"right",			//44
									"Medbay"	=	"brig",				//45
									"Science"	=	"Cargo",			//46
									"borg"		=	"human",			//47
									"HoS"		=	"CMO",				//48
									"QM"		=	"captain",			//49
									"HoP"		=	"RD",				//50
									"plasma"	=	"oxygen",			//51
									"n2o"		=	"co2",				//52
									"opposite"	=	"same",				//53
									"Ian"		=	"Runtime",			//54
									"dog"		=	"cat",				//55
									"chaplain"	=	"cultist",			//56
									"rune"		=	"graffiti",			//57
									"hot"		=	"cold",				//58
									"on fire"	=	"freezing",			//59
									"breached"	=	"sealed",			//60
									"open"		=	"close",			//61
									"opened"	=	"closed",			//62
									"bolt"		=	"unbolt",			//63
									"bolted"	=	"unbolted",			//64
									"fore"		=	"aft",				//65
									"port"		=	"starboard",		//66
									"should've"	=	"shouldn't have")	//67