//For lists of words to be used with viruses.
var/global/list/virus_word_list_1
var/global/list/virus_word_list_2

/datum/disease2/proc/initialize_word_lists()
	virus_word_list_1 = list("to",			//1
								"and",		//2
								"in",		//3
								"that",		//4
								"I",		//5
								"on",		//6
								"with",		//7
								"he",		//8
								"we",		//9
								"his",		//10
								"will",		//11
								"my",		//12
								"mine",		//13
								"one",		//14
								"all",		//15
								"would",	//16
								"there",	//17
								"their",	//18
								"what",		//19
								"up",		//20
								"go",		//21
								"when",		//22
								"no",		//23
								"him",		//24
								"take",		//25
								"into",		//26
								"good",		//27
								"some",		//28
								"could",	//29
								"them",		//30
								"see",		//31
								"now",		//32
								"look",		//33
								"over",		//34
								"think",	//35
								"back",		//36
								"after",	//37
								"how",		//38
								"first",	//39
								"new",		//40
								"most",		//41
								"help",		//42
								"hurt",		//43
								"left",		//44
								"Medbay",	//45
								"Science",	//46
								"borg",		//47
								"HoS",		//48
								"QM",		//49
								"HoP",		//50
								"plasma",	//51
								"n2o",		//52
								"opposite",	//53
								"Ian",		//54
								"dog",		//55
								"chaplain",	//56
								"rune",		//57
								"hot",		//58
								"on fire",	//59
								"breached",	//60
								"open",		//61
								"opened",	//62
								"bolt",		//63
								"bolted")	//64

	virus_word_list_2 = list("from",		//1
								"not",		//2
								"out",		//3
								"this",		//4
								"you",		//5
								"off",		//6
								"without",	//7
								"she",		//8
								"they",		//9
								"her",		//10
								"won't",	//11
								"your",		//12
								"yours",	//13
								"two",		//14
								"none",		//15
								"wouldn't",	//16
								"here",		//17
								"our",		//18
								"who",		//19
								"down",		//20
								"come",		//21
								"where",	//22
								"yes",		//23
								"her",		//24
								"give",		//25
								"out of",	//26
								"bad",		//27
								"none",		//28
								"couldn't",	//29
								"us",		//30
								"hear",		//31
								"later",	//32
								"listen",	//33
								"under",	//34
								"feel",		//35
								"front",	//36
								"before",	//37
								"why",		//38
								"last",		//39
								"old",		//40
								"least",	//41
								"kill",		//42
								"heal",		//43
								"right",	//44
								"brig",		//45
								"Cargo",	//46
								"human",	//47
								"CMO",		//48
								"captain",	//49
								"RD",		//50
								"oxgyen",	//51
								"co2",		//52
								"same",		//53
								"Runtime",	//54
								"cat",		//55
								"cultist",	//56
								"graffiti",	//57
								"cold",		//58
								"freezing",	//59
								"sealed",	//60
								"close",	//61
								"closed",	//62
								"unbolt",	//63
								"unbolted")	//64