/proc/captain_announce(var/text)
	for(var/mob/M in player_list)
		if(!istype(M,/mob/new_player) && M.client)
			M << sound('sound/vox/_doop.wav')
			to_chat(M, "<h1 class='alert'>Priority Announcement</h1><span class='alert'>[html_encode(text)]</span><br>")
