/mob/living/silicon/hivebot/examine(mob/user)
	to_chat(user, "<span class='notice'>*---------*</span>")
	to_chat(user, text("<span class='notice'>This is [bicon(src)] <B>[name]</B>!</span>"))
	if (stat == 2)
		to_chat(user, text("<span class='warning'>[name] is powered-down.</span>"))
	if (getBruteLoss())
		if (getBruteLoss() < 75)
			to_chat(user, text("<span class='warning'>[name] looks slightly dented</span>"))
		else
			to_chat(user, text("<span class='danger'>[name] looks severely dented!</span>"))
	if (getFireLoss())
		if (getFireLoss() < 75)
			to_chat(user, text("<span class='warning'>[name] looks slightly burnt!</span>"))
		else
			to_chat(user, text("<span class='danger'>[name] looks severely burnt!</span>"))
	if (stat == 1)
		to_chat(user, text("<span class='warning'>[name] doesn't seem to be responding.</span>"))
