#define BLOBCORECOSTINC 50
#define BLOBCOREBASECOST 100
#define BLOBSHICOST 5
#define BLOBRESCOST 30
#define BLOBFACCOST 45
#define BLOBNODCOST 15
#define BLOBATTCOST 15
#define BLOBRALCOST 5
#define BLOBTAUNTCOST 15

#define BLOBNDPOINTINC 10