#define BLOBCORECOSTINC 50
#define BLOBCOREBASECOST 100
#define BLOBSHICOST 10
#define BLOBRESCOST 40
#define BLOBFACCOST 60
#define BLOBNODCOST 60
#define BLOBATTCOST 5
#define BLOBRALCOST 5
#define BLOBTAUNTCOST 15

#define BLOBNDPOINTINC 10