name: Make changelogs

on:
  push:
    branches:
      - Bleeding-Edge

jobs:
  MakeCL:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 25
      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install depends
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/changelog/requirements.txt
      - name: Make CL
        env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} Use this instead if you have unprotected branches
          GITHUB_TOKEN: ${{ secrets.CL_TOKEN }}
          GIT_EMAIL: "29069174+toomykins@users.noreply.github.com"
          GIT_NAME: "toomykins"
        run: python tools/changelog/gen_cl.py
      - name: Check for running instances of Workflow A
        id: check_workflows
        run: |
          runs=$(curl -s -H "Authorization: token ${{ secrets.CL_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/make_changelogs.yml/runs?status=in_progress")
          echo "runs=$runs" >> $GITHUB_ENV
      - name: Trigger Compile Changelogs
        if: env.runs == "[]"
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.CL_TOKEN }}" \
          https://api.github.com/repos/your-username/your-repo/dispatches \
          -d '{"event_type":"trigger-compile-changelogs"}'

