name: Make changelogs

on:
  push:
    branches:
      - Bleeding-Edge

jobs:
  MakeCL:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 25
      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install depends
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/changelog/requirements.txt
      - name: Make CL
        env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} Use this instead if you have unprotected branches
          GITHUB_TOKEN: ${{ secrets.CL_TOKEN }}
          GIT_EMAIL: "29069174+toomykins@users.noreply.github.com"
          GIT_NAME: "toomykins"
        run: python tools/changelog/gen_cl.py
      - name: Trigger compile changelog
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: trigger-compile-changelog